/*
 * This source file was generated by the Gradle 'init' task
 */
package demo1_2;

import java.util.List;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

	public static void main(String[] args) {
		new Demo2().initialize();
	}

	public void initialize() {

      // Upcasting implicite: sous-classes vues comme Personnage
        List<Personnage> equipe = List.of(
            new Guerrier("Arthas"),
            new Mage("Jaina")
        );

        Mission mission = new MissionCombat("combat final");

        // POLYMORPHISME: le même code appelle la "bonne" implémentation
        for (Personnage p : equipe) {
            mission.executer(p);
        }

        // instanceof (pattern matching) + transtypage sécurisé
        Personnage a = equipe.get(0); // Guerrier
        if (a instanceof Guerrier g) {
            g.coupPuissant(); // OK, accès à l’API Guerrier
        }

        Personnage b = equipe.get(1); // Mage
        if (b instanceof Mage m) {
            m.lancerSort(); // OK, accès à l’API Mage
        }

        // Downcast "classique" (évitez sans instanceof)
        Personnage x = new Guerrier("Thorin");
        if (x instanceof Guerrier) {
            Guerrier gx = (Guerrier) x; // cast explicite
            gx.coupPuissant();
        }

        // Mauvais cast (exemple à NE PAS faire) : ClassCastException
        // Guerrier gg = (Guerrier) new Mage("FauxGuerrier"); // NE PAS FAIRE
    }

}
